#!/bin/sh
# this is a wrapper scripts that sets up the gradle cache and zips it after execution so that it can
# be easily transfered to cloud storage with gsutil
unzip -o -q cache.zip
./gradlew $@
status=$?
zip -qr cache.zip .gradle
echo "Exit status is: $status"
exit $status